//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_25_7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewUser
    {
        public int id { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public string userName { get; set; }
        public Nullable<int> Age { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    }
}
