// <auto-generated />
namespace MVC_Code_first_17_9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TeacherCourses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeacherCourses));
        
        string IMigrationMetadata.Id
        {
            get { return "202409181357435_TeacherCourses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
