// <auto-generated />
namespace MVC_Code_first_19_9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class TablesAndLoginPage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TablesAndLoginPage));
        
        string IMigrationMetadata.Id
        {
            get { return "202409211016301_TablesAndLoginPage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
